name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Change working directory
      run: cd weather-booking-client

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test 